LongInt.out: LongIntMain.o LongInt.o
	g++ -g -Wall -o LongInt.out LongIntMain.o LongInt.o

LongIntMain.o: LongIntMain.cpp LongInt.h
	g++ -g -Wall -c -o LongIntMain.o LongIntMain.cpp

LongInt.o: LongInt.cpp LongInt.h
	g++ -g -Wall -c -o LongInt.o LongInt.cpp